export type MCQ = {
  id: string;
  section: string;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
  explanation: string;
};

const q = (id: string, section: string, question: string, A: string, B: string, C: string, D: string, correct: "A"|"B"|"C"|"D", explanation: string): MCQ =>
  ({ id, section, question, options: { A, B, C, D }, correct, explanation });

export const DIAGNOSTIC_QUESTIONS_P2: MCQ[] = [
  // ── Section A: Financial Statement Analysis ──
  q("P2A1","A","Horizontal analysis compares financial data:","Across different companies","Across different time periods","Across different departments","Against industry benchmarks","B","Horizontal (trend) analysis compares financial data across multiple time periods to identify trends and growth rates."),
  q("P2A2","A","The current ratio is calculated as:","Current assets / Total assets","Current assets / Current liabilities","Net income / Current liabilities","Total assets / Total liabilities","B","Current ratio = Current assets / Current liabilities. It measures short-term liquidity."),
  q("P2A3","A","A high debt-to-equity ratio indicates:","Low financial leverage","High financial leverage and more risk","Strong liquidity","High profitability","B","A high D/E ratio means the firm is heavily financed by debt, implying greater financial risk and leverage."),
  q("P2A4","A","The asset turnover ratio measures:","How efficiently a firm uses assets to generate sales","Profitability per asset dollar","The ratio of fixed to current assets","Return on total assets","A","Asset turnover = Net sales / Average total assets. It indicates how efficiently assets are deployed to generate revenue."),
  q("P2A5","A","Return on equity (ROE) is best decomposed using:","The Gordon Growth Model","The DuPont analysis framework","The CAPM model","The Altman Z-score","B","DuPont analysis breaks ROE into profit margin × asset turnover × financial leverage, identifying sources of performance."),
  q("P2A6","A","Earnings per share (EPS) is calculated as:","Net income / Total shares authorised","Net income available to common shareholders / Weighted average common shares outstanding","Operating income / Total shares","EBIT / Total shares","B","Basic EPS = Net income available to common shareholders ÷ Weighted average common shares outstanding."),
  q("P2A7","A","Diluted EPS differs from basic EPS because it includes:","Preferred dividends","The effect of all potentially dilutive securities","Only convertible bonds","Treasury stock","B","Diluted EPS includes the dilutive effect of options, warrants, convertible bonds, and convertible preferred stock."),
  q("P2A8","A","The price-to-earnings (P/E) ratio indicates:","How much investors pay per dollar of earnings","The dividend payout rate","The firm's asset turnover","The firm's debt level","A","P/E = Market price per share / EPS. It shows how much investors are willing to pay per dollar of earnings."),
  q("P2A9","A","Earnings quality is considered HIGH when earnings:","Are driven by non-recurring items","Are sustainable, repeatable, and backed by cash flows","Show rapid growth","Are reported under IFRS only","B","High earnings quality means earnings are persistent, repeatable, and supported by actual operating cash flows — not one-time items."),
  q("P2A10","A","The interest coverage ratio (times interest earned) is:","EBIT / Interest expense","Net income / Interest expense","EBITDA / Total debt","Operating cash flow / Current liabilities","A","Interest coverage = EBIT / Interest expense. It measures how many times the firm can cover its interest charges from operating income."),
  q("P2A11","A","When a foreign subsidiary's functional currency differs from the parent's, financial statements are:","Restated using the historical rate for all items","Translated using the current rate method or temporal method","Ignored in consolidation","Converted using the average rate for all items","B","Foreign subsidiary financials are translated — using the current rate method when the functional currency is the subsidiary's local currency, or the temporal method otherwise."),
  q("P2A12","A","Inflation generally causes financial ratios to be:","More accurate over time","Distorted because historical cost values diverge from current values","Unaffected","More conservative","B","Inflation distorts ratio analysis because assets recorded at historical cost understate current values, making ratios like asset turnover and ROA misleading."),
  q("P2A13","A","A change in accounting principle requires:","Prospective application only","Retrospective restatement of prior periods (generally)","No disclosure","Immediate expensing of the change","B","Changes in accounting principles generally require retrospective restatement of prior-period financial statements for comparability."),
  q("P2A14","A","Book value per share is:","Market price / EPS","Total stockholders' equity / Shares outstanding","Net income / Shares outstanding","Total assets / Shares outstanding","B","Book value per share = Total stockholders' equity / Shares outstanding. It represents the accounting net worth per share."),
  q("P2A15","A","Common-size income statement expresses each item as a percentage of:","Total assets","Net sales (revenue)","Net income","Total liabilities","B","In a common-size income statement, each line item is expressed as a percentage of net sales, enabling cross-company comparison."),

  // ── Section B: Corporate Finance ──
  q("P2B1","B","The Capital Asset Pricing Model (CAPM) states that expected return equals:","Risk-free rate + beta × (market return − risk-free rate)","Risk-free rate + alpha","Beta × market return","Dividend yield + growth rate","A","CAPM: E(R) = Rf + β(Rm − Rf). It prices the systematic risk of an asset relative to the market."),
  q("P2B2","B","Beta measures:","Total risk of a security","Systematic (market) risk of a security","Unsystematic risk","Liquidity risk","B","Beta measures a security's sensitivity to market movements — its systematic (non-diversifiable) risk."),
  q("P2B3","B","The Weighted Average Cost of Capital (WACC) represents:","The cost of equity only","The blended cost of all financing sources weighted by their market-value proportions","The average interest rate on debt","The dividend yield","B","WACC = (E/V)×Re + (D/V)×Rd×(1−T). It weights the after-tax cost of each capital source by its proportion of total capital."),
  q("P2B4","B","A bond's duration measures:","The bond's coupon rate","The weighted average time to receive cash flows, measuring interest rate sensitivity","The credit rating of the bond","The bond's yield to maturity","B","Duration is the weighted average time to receive a bond's cash flows. It measures price sensitivity to interest rate changes."),
  q("P2B5","B","The Net Present Value (NPV) decision rule states:","Accept if NPV = 0","Accept if NPV > 0","Accept if NPV < 0","Accept if NPV > IRR","B","Accept a project if NPV > 0, meaning it adds value to the firm. Reject if NPV < 0."),
  q("P2B6","B","A call option gives the holder the right to:","Sell the underlying asset at the strike price","Buy the underlying asset at the strike price","Receive dividends","Short-sell the stock","B","A call option grants the right (not obligation) to buy the underlying asset at the strike price before or at expiration."),
  q("P2B7","B","Working capital is defined as:","Total assets minus total liabilities","Current assets minus current liabilities","Fixed assets minus long-term debt","Cash plus receivables","B","Net working capital = Current assets − Current liabilities. It measures short-term operational liquidity."),
  q("P2B8","B","The optimal dividend policy according to MM (Modigliani-Miller) in perfect markets is:","Always pay maximum dividends","Always retain all earnings","Dividend policy is irrelevant to firm value","Pay dividends only from debt proceeds","C","MM's dividend irrelevance theorem states that in perfect capital markets, dividend policy does not affect firm value."),
  q("P2B9","B","A forward contract differs from a futures contract in that forwards are:","Exchange-traded and standardised","Privately negotiated and not exchange-traded","Settled daily through marking to market","Regulated by the SEC","B","Forward contracts are private, customised agreements between two parties — not exchange-traded or standardised like futures."),
  q("P2B10","B","The internal rate of return (IRR) is:","The discount rate that makes NPV equal to zero","The return on equity","The hurdle rate set by management","The weighted average cost of capital","A","IRR is the discount rate that sets NPV = 0. Accept a project if IRR > required rate of return (hurdle rate)."),
  q("P2B11","B","Trade credit (accounts payable) is a form of:","Long-term financing","Spontaneous short-term financing","Equity financing","Bond financing","B","Trade credit arises spontaneously from normal business operations — suppliers extend credit automatically as purchases are made."),
  q("P2B12","B","A merger creates value primarily through:","Reducing revenue","Operating synergies, financial synergies, or market power","Increasing interest expense","Eliminating equity","B","Mergers are justified when synergies (cost savings, revenue enhancements, tax benefits) make the combined entity worth more than the sum of parts."),
  q("P2B13","B","Purchasing power parity (PPP) states that exchange rates adjust to:","Equalise interest rates between countries","Equalise price levels between countries","Maximise trade balances","Match gold reserves","B","PPP holds that exchange rates between two currencies will adjust so that identical goods cost the same in both countries."),
  q("P2B14","B","The yield curve plots:","Stock prices vs. time","Bond yields vs. maturities","Risk vs. return","Dividends vs. price","B","The yield curve shows the relationship between bond yields (interest rates) and their maturities at a given point in time."),
  q("P2B15","B","Factoring receivables means:","Collecting receivables internally","Selling receivables to a third party at a discount","Writing off bad debts","Securitising long-term debt","B","Factoring involves selling accounts receivable to a factor (third party) at a discount in exchange for immediate cash."),

  // ── Section C: Business Decision Analysis ──
  q("P2C1","C","The break-even point in units is calculated as:","Fixed costs / Contribution margin per unit","Total costs / Selling price","Variable costs / Selling price","Fixed costs / Selling price","A","Break-even units = Fixed costs / (Selling price − Variable cost per unit) = Fixed costs / CM per unit."),
  q("P2C2","C","Contribution margin equals:","Sales minus total costs","Sales minus variable costs","Sales minus fixed costs","Gross profit minus selling expenses","B","Contribution margin = Sales − Variable costs. It represents the amount available to cover fixed costs and generate profit."),
  q("P2C3","C","The margin of safety measures:","Break-even sales","The excess of actual (or budgeted) sales over break-even sales","Variable cost per unit","Fixed cost coverage","B","Margin of safety = Actual sales − Break-even sales. It shows how much sales can fall before the firm reaches break-even."),
  q("P2C4","C","In a make-or-buy decision, the relevant costs are:","All historical costs","Incremental (avoidable) costs plus opportunity costs","Sunk costs","Full absorption costs","B","Only relevant (incremental) costs that differ between alternatives matter — plus any opportunity cost of capacity used."),
  q("P2C5","C","A special order should be accepted if:","Its price exceeds average total cost","It generates a positive contribution margin and does not affect regular sales","It covers fixed costs fully","Its price equals variable cost","B","Accept a special order if the incremental revenue exceeds incremental variable costs (positive CM) and no regular sales are displaced."),
  q("P2C6","C","The sell-or-process-further decision should be based on:","Historical joint costs","Incremental revenue vs. incremental processing costs beyond split-off","Total revenue from both options","Fixed cost allocation","B","Joint costs are sunk at the split-off point. Only the incremental revenue and costs of further processing are relevant."),
  q("P2C7","C","Price elasticity of demand measures:","How supply changes with price","How quantity demanded changes proportionally with price","How costs change with volume","How profit changes with price","B","Price elasticity = % change in quantity demanded / % change in price. Elastic demand (|e|>1) means quantity is sensitive to price."),
  q("P2C8","C","Target costing sets the cost target as:","Actual cost + markup","Market price − desired profit margin","Variable cost + fixed cost","Standard cost × volume","B","Target cost = Competitive market price − Desired profit margin. It drives cost reduction to achieve the required margin."),
  q("P2C9","C","A company operating in a perfectly competitive market is a:","Price maker","Price taker","Monopolist","Oligopolist","B","In perfect competition, firms are price takers — they have no pricing power and must accept the market price."),
  q("P2C10","C","Operating leverage is high when:","Variable costs are high relative to fixed costs","Fixed costs are high relative to variable costs","The break-even point is low","The contribution margin ratio is low","B","High fixed costs relative to variable costs create high operating leverage — small changes in sales cause larger swings in profit."),
  q("P2C11","C","The product life cycle pricing strategy that sets a high initial price is called:","Penetration pricing","Price skimming","Cost-plus pricing","Transfer pricing","B","Price skimming sets a high initial price to capture consumer surplus from early adopters, then lowers price over time."),
  q("P2C12","C","Relevant costs in a disinvestment decision include:","Accumulated depreciation","Book value of the asset","Salvage value and avoidable operating costs","Historical purchase price","C","In disinvestment decisions, relevant items are future cash flows: salvage proceeds, and costs that can be avoided by divesting."),
  q("P2C13","C","When a firm has a binding capacity constraint, it should prioritise products by:","Highest selling price","Highest contribution margin per unit of the constraining resource","Lowest variable cost","Highest total revenue","B","With a scarce resource, maximise total CM by ranking products on CM per unit of the bottleneck resource (constraint)."),
  q("P2C14","C","The CVP assumption that all costs are either fixed or variable implies:","Costs are non-linear","The relevant range is the entire production range","Costs behave linearly within the relevant range","Step-fixed costs do not exist","C","CVP analysis assumes cost linearity within the relevant range — a simplification that holds reasonably well over normal operating levels."),
  q("P2C15","C","A penetration pricing strategy sets the initial price:","High to recover development costs quickly","Low to gain market share rapidly","Equal to competitors","Based on cost plus a standard markup","B","Penetration pricing uses a low price to attract customers and build market share quickly, then raises prices once established."),

  // ── Section D: Enterprise Risk Management ──
  q("P2D1","D","Enterprise Risk Management (ERM) is best described as:","A departmental compliance checklist","A holistic, board-level process to identify, assess, and manage risks across the organisation","A purely financial risk model","An IT security framework","B","ERM is an enterprise-wide, strategic process overseen by the board and senior management to manage all categories of risk."),
  q("P2D2","D","The COSO ERM framework identifies which risk response strategies?","Accept, transfer, reduce, and avoid","Ignore, monitor, escalate, and report","Diversify, hedge, insure, and exit","Control, detect, prevent, and correct","A","COSO ERM risk responses: Accept (tolerate), Transfer (share), Reduce (mitigate), and Avoid (exit the activity)."),
  q("P2D3","D","Residual risk is:","The risk before any controls","The risk remaining after management's risk response","The highest possible risk level","Regulatory risk only","B","Residual risk = Inherent risk after applying risk responses and controls. It is the risk the organisation retains."),
  q("P2D4","D","Risk appetite is best defined as:","The amount of risk the firm has incurred","The maximum amount of risk the firm is willing to accept in pursuit of its objectives","The firm's ability to absorb losses","The regulatory capital requirement","B","Risk appetite is the total risk an organisation is prepared to accept to achieve its strategic objectives — set by the board."),
  q("P2D5","D","Operational risk includes:","Credit default by customers","Loss from market price movements","Losses from failed internal processes, people, or systems","Interest rate changes","C","Operational risk arises from failures in people, processes, systems, or external events — distinct from market or credit risk."),
  q("P2D6","D","A risk heat map plots risks by:","Cost and time","Likelihood and impact","Asset class and duration","Probability and return","B","A risk heat map visually ranks risks by their probability (likelihood) of occurrence and their potential impact."),
  q("P2D7","D","Systematic risk (market risk) is:","Diversifiable through a portfolio","Non-diversifiable and affects the entire market","Company-specific risk","Eliminated by hedging","B","Systematic risk cannot be diversified away — it affects all assets in the market. Only unsystematic risk is reduced by diversification."),
  q("P2D8","D","Value at Risk (VaR) measures:","The expected return of a portfolio","The maximum potential loss over a period at a given confidence level","The total volatility of a portfolio","The minimum guaranteed return","B","VaR estimates the maximum loss expected over a specific time horizon at a given confidence level (e.g., 95% or 99%)."),
  q("P2D9","D","Reputational risk arises from:","Market price movements","Negative public perception or damage to brand image","Credit defaults","System outages","B","Reputational risk is the risk of damage to a firm's brand, relationships, or standing that can lead to revenue loss."),
  q("P2D10","D","Capital adequacy requirements ensure that financial institutions:","Maximise leverage","Hold sufficient capital to absorb unexpected losses","Minimise regulatory reporting","Avoid equity financing","B","Capital adequacy rules (e.g., Basel III) require banks to hold minimum capital buffers to absorb losses and protect depositors."),
  q("P2D11","D","A key risk indicator (KRI) is:","A financial metric only","A forward-looking metric that signals emerging risks","A lagging performance indicator","A regulatory compliance measure","B","KRIs are early-warning metrics that alert management to increasing risk exposure before losses actually occur."),
  q("P2D12","D","The primary goal of a risk register is to:","Eliminate all identified risks","Document, track, and manage identified risks and their responses","Assign all risks to insurance","Report risks only to external auditors","B","A risk register is a central repository listing all identified risks, their owners, likelihood, impact, and planned responses."),
  q("P2D13","D","Hedging a foreign currency exposure reduces:","Profitability","Systematic risk","Transaction or translation risk from currency fluctuations","Liquidity risk","C","Currency hedges (forwards, options, swaps) reduce transaction risk (future cash flows) and translation risk (balance sheet) from FX movements."),
  q("P2D14","D","Stress testing in risk management involves:","Testing employee performance","Evaluating portfolio performance under extreme adverse scenarios","Running normal operating simulations","Benchmarking against competitors","B","Stress testing assesses how a portfolio or firm would perform under severe but plausible adverse scenarios (e.g., market crash)."),
  q("P2D15","D","Compliance risk is the risk of:","Market price volatility","Legal penalties or reputational damage from failing to comply with laws and regulations","Poor investment returns","Technology failures","B","Compliance risk arises when an organisation fails to adhere to applicable laws, regulations, or internal policies — leading to fines or sanctions."),

  // ── Section E: Capital Investment Decisions ──
  q("P2E1","E","The payback period method's main weakness is that it:","Is difficult to calculate","Ignores cash flows after the payback period and the time value of money","Always leads to wrong decisions","Requires a discount rate","B","The payback method ignores both the time value of money and all cash flows beyond the payback period — it focuses only on liquidity."),
  q("P2E2","E","The net present value (NPV) method discounts cash flows at:","The payback period","The required rate of return (cost of capital)","The inflation rate","The internal rate of return","B","NPV discounts all expected cash flows at the firm's required rate of return (hurdle rate / WACC) to determine value added."),
  q("P2E3","E","If a project's IRR exceeds the required rate of return, the project should be:","Rejected","Accepted, as it adds value","Deferred","Evaluated only on payback","B","If IRR > required rate of return (hurdle rate), the project generates returns above the cost of capital and should be accepted."),
  q("P2E4","E","The profitability index (PI) is calculated as:","NPV / Initial investment","(NPV + Initial investment) / Initial investment","Net income / Initial investment","IRR / Cost of capital","B","PI = (PV of future cash flows) / Initial investment = 1 + (NPV / Initial investment). PI > 1 signals value creation."),
  q("P2E5","E","Relevant cash flows for capital investment analysis include:","Sunk costs","Incremental after-tax operating cash flows and terminal value","Historical costs","Allocated overhead","B","Only incremental (marginal) after-tax cash flows — including working capital changes and salvage value — are relevant to capital budgeting."),
  q("P2E6","E","The modified internal rate of return (MIRR) assumes reinvestment of cash flows at:","The IRR","The cost of capital (required rate of return)","The risk-free rate","The average accounting return","B","MIRR assumes interim cash flows are reinvested at the firm's cost of capital — a more realistic assumption than the IRR's reinvestment assumption."),
  q("P2E7","E","Capital rationing occurs when:","A firm has unlimited capital","A firm has more acceptable projects than available capital","All projects have negative NPV","The IRR equals the cost of capital","B","Capital rationing forces firms to prioritise among positive-NPV projects because the available capital budget is constrained."),
  q("P2E8","E","Depreciation affects capital budgeting primarily because:","It is a direct cash outflow","It reduces taxable income, thereby creating a tax shield (cash saving)","It increases the project's salvage value","It is always irrelevant","B","Depreciation is non-cash, but it reduces taxable income — generating a tax shield (= depreciation × tax rate) that is a real cash benefit."),
  q("P2E9","E","A real option in capital investment gives management the right to:","Guarantee a fixed return","Adapt decisions (expand, delay, abandon) in response to future information","Avoid all downside risk","Fix the discount rate","B","Real options (e.g., option to expand, defer, or abandon) give management flexibility to revise investment decisions — creating value beyond static NPV."),
  q("P2E10","E","The accounting rate of return (ARR) is criticised because:","It is hard to compute","It uses accounting income (not cash flows) and ignores the time value of money","It requires a hurdle rate","It is not related to profitability","B","ARR = Average annual net income / Average investment. It ignores TVM and uses accrual income rather than cash flows."),
  q("P2E11","E","When two mutually exclusive projects have conflicting NPV and IRR rankings, preference should be given to:","The higher IRR","The higher NPV, as it maximises shareholder wealth","The shorter payback","The lower initial cost","B","For mutually exclusive projects, choose the higher NPV — it directly measures value added to shareholders, unlike IRR which can be misleading."),
  q("P2E12","E","The terminal cash flow in capital budgeting includes:","Only operating profit in the final year","After-tax salvage value and recovery of net working capital","Sunk costs","Allocated overhead","B","Terminal cash flows = After-tax salvage (disposal proceeds net of taxes) + Recovery of net working capital previously invested."),
  q("P2E13","E","Sensitivity analysis in capital budgeting tests:","Multiple project alternatives simultaneously","How NPV changes when one input variable is varied, holding others constant","The probability distribution of outcomes","Historical cost trends","B","Sensitivity analysis (what-if) varies one input (e.g., sales volume, price) while holding others fixed to find which variable most affects NPV."),
  q("P2E14","E","A higher discount rate applied to a project's cash flows will:","Increase the NPV","Decrease the NPV","Not affect the NPV","Increase the IRR","B","A higher discount rate reduces the present value of future cash flows — lowering NPV. This reflects greater risk or cost of capital."),
  q("P2E15","E","The discounted payback period improves on the simple payback period by:","Ignoring risk","Accounting for the time value of money in measuring payback","Using accounting income","Including sunk costs","B","Discounted payback discounts cash flows before computing the payback period, addressing the TVM limitation of simple payback."),

  // ── Section F: Professional Ethics ──
  q("P2F1","F","The IMA Statement of Ethical Professional Practice requires members to uphold which core principles?","Profit, efficiency, innovation, and leadership","Honesty, fairness, objectivity, and responsibility","Compliance, accuracy, disclosure, and service","Competence, trust, loyalty, and compliance","B","The IMA's four principles are: Honesty, Fairness, Objectivity, and Responsibility — the foundation of ethical behaviour for management accountants."),
  q("P2F2","F","The IMA's confidentiality standard requires members to:","Disclose all information to shareholders","Refrain from disclosing confidential information except when legally required or authorised","Share information only with auditors","Publish all financial data","B","IMA confidentiality: members must keep information confidential, except when disclosure is legally obligated or professionally necessary."),
  q("P2F3","F","The fraud triangle consists of:","Motive, means, and opportunity","Pressure, opportunity, and rationalisation","Greed, deception, and concealment","Risk, reward, and rationality","B","The fraud triangle identifies three conditions present in most frauds: Pressure (motive), Opportunity (means), and Rationalisation (justification)."),
  q("P2F4","F","When a management accountant faces an ethical conflict, the first step recommended by the IMA is to:","Resign immediately","Report to external regulators","Discuss the issue with the immediate supervisor first","Contact the media","C","The IMA ethics resolution process starts internally — raise the concern with the immediate supervisor, then escalate through channels if unresolved."),
  q("P2F5","F","A whistleblower is someone who:","Covers up unethical behaviour","Reports suspected wrongdoing or illegal activity","Performs an internal audit","Manages risk","B","A whistleblower reports known or suspected illegal or unethical conduct — typically protected from retaliation under laws like SOX."),
  q("P2F6","F","Corporate social responsibility (CSR) refers to:","Maximising short-term shareholder returns","A business's commitment to ethical behaviour, social good, and environmental stewardship beyond legal requirements","Compliance with tax law","Reducing costs through outsourcing","B","CSR involves voluntary actions a company takes to be socially accountable, considering stakeholder impacts beyond legal obligations."),
  q("P2F7","F","Sustainability reporting discloses information about:","Only financial performance","Environmental, social, and governance (ESG) impacts","Employee compensation only","Tax strategy only","B","Sustainability (ESG) reporting covers environmental impact, social practices (labour, community), and governance — alongside financial performance."),
  q("P2F8","F","The IMA's competence standard requires members to:","Maximise profitability","Maintain professional knowledge and skills to provide competent services","Avoid all conflicts of interest","Prioritise employer interests over ethics","B","IMA competence: members must maintain appropriate professional knowledge, skills, and perform duties in accordance with relevant standards."),
  q("P2F9","F","Data ethics concerns which of the following?","Physical security of hardware","Responsible collection, use, and protection of data, respecting privacy and fairness","Maximising data monetisation","Storing data in the cloud","B","Data ethics involves the moral obligations around data — including privacy, consent, bias, fairness, and responsible use of personal and organisational information."),
  q("P2F10","F","An ethical organisational culture is primarily shaped by:","Company size","Tone at the top — leadership behaviour and values","Profit margins","Regulatory environment alone","B","Research consistently shows that management behaviour and 'tone at the top' is the most powerful driver of an ethical culture."),
  q("P2F11","F","The Foreign Corrupt Practices Act (FCPA) applies to:","Only domestic transactions","US companies and foreign companies listed on US exchanges, prohibiting bribery of foreign officials","Only federal contractors","Companies with revenue > $1 billion","B","The FCPA prohibits US issuers, domestic concerns, and foreign companies listed in the US from bribing foreign government officials."),
  q("P2F12","F","Greenwashing refers to:","Genuine sustainability improvements","Making misleading claims about environmental practices to appear more sustainable","Environmental reporting under IFRS","Carbon offset purchases","B","Greenwashing is the practice of making unsubstantiated or misleading environmental claims to gain marketing advantage without genuine sustainability commitment."),
  q("P2F13","F","An independence threat to an accountant's objectivity occurs when:","The accountant follows GAAP","The accountant has a financial or personal interest that could compromise judgement","The accountant charges standard fees","The accountant prepares tax returns","B","Objectivity is threatened by financial interests (self-interest), close personal relationships (familiarity), advocacy, intimidation, or self-review threats."),
  q("P2F14","F","The IMA's credibility standard requires members to:","Disclose all proprietary information","Communicate information fairly, objectively, and disclose all relevant information","Avoid preparing reports","Act only in self-interest","B","IMA credibility standard: communicate information fairly and objectively, disclose all relevant information, and disclose delays or deficiencies."),
  q("P2F15","F","Business fraud most commonly involves:","External theft of physical assets","Asset misappropriation, financial statement fraud, or corruption by insiders","Cybersecurity breaches only","Customer fraud exclusively","B","The ACFE Report to the Nations identifies three major fraud categories: asset misappropriation (most common), corruption, and financial statement fraud."),
];

export const SECTIONS_LIST_P2 = ["A","B","C","D","E","F"] as const;
export type SectionIdP2 = typeof SECTIONS_LIST_P2[number];

export function getQuestionsForSectionP2(section: SectionIdP2): MCQ[] {
  return DIAGNOSTIC_QUESTIONS_P2.filter(q => q.section === section);
}
