export type MCQ = {
  id: string;
  section: string;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
  explanation: string;
};

const q = (id: string, section: string, question: string, A: string, B: string, C: string, D: string, correct: "A"|"B"|"C"|"D", explanation: string): MCQ =>
  ({ id, section, question, options: { A, B, C, D }, correct, explanation });

export const DIAGNOSTIC_QUESTIONS: MCQ[] = [
  // ── Section A: External Financial Reporting ──
  q("A1","A","Which financial statement shows a company's financial position at a specific point in time?","Income Statement","Balance Sheet","Statement of Cash Flows","Statement of Retained Earnings","B","The Balance Sheet (Statement of Financial Position) presents assets, liabilities, and equity at a specific date."),
  q("A2","A","Under FIFO during a period of rising prices, ending inventory is:","Lower than LIFO","Higher than LIFO","Equal to LIFO","Equal to weighted average","B","FIFO assigns older (lower) costs to COGS, leaving newer (higher) costs in ending inventory."),
  q("A3","A","The indirect method of the cash flow statement begins with:","Cash received from customers","Net income","Operating income","Gross profit","B","The indirect method starts with net income and adjusts for non-cash items and working capital changes."),
  q("A4","A","Goodwill arising from a business combination is:","Amortized over 40 years","Tested annually for impairment","Expensed immediately","Amortized over its useful life","B","Under US GAAP, goodwill is not amortized but tested for impairment at least annually."),
  q("A5","A","Which depreciation method results in the highest depreciation in the first year?","Straight-line","Units of production","Double-declining balance","Sum-of-years digits","C","Double-declining balance applies twice the straight-line rate to the book value, front-loading depreciation."),
  q("A6","A","Revenue is recognized under ASC 606 when:","Cash is received","The contract is signed","Performance obligations are satisfied","The invoice is issued","C","Revenue is recognized when (or as) performance obligations are transferred to the customer."),
  q("A7","A","A finance lease transfers:","Only legal title","Substantially all risks and rewards","Only operating control","None of the above","B","A finance lease transfers substantially all risks and rewards of ownership to the lessee."),
  q("A8","A","Which investment uses the equity method?","Less than 20% ownership","20%–50% ownership with significant influence","More than 50% ownership","Debt securities","B","The equity method is used for investments giving significant influence, typically 20–50% ownership."),
  q("A9","A","Deferred tax liability arises when:","Tax expense > taxes payable","Taxes payable > tax expense","Taxable income > accounting income","A tax loss carryforward exists","A","A deferred tax liability arises when book income exceeds taxable income, meaning more tax will be owed later."),
  q("A10","A","Integrated reporting primarily aims to explain:","Only financial performance","How strategy creates value over time","Regulatory compliance","Tax optimization","B","Integrated reporting shows how an organisation creates value over time using financial and non-financial capitals."),
  q("A11","A","Under LIFO, during periods of rising prices, cost of goods sold is:","Lower than FIFO","Higher than FIFO","Equal to FIFO","Cannot be determined","B","LIFO uses the most recent (higher) costs for COGS, resulting in higher COGS than FIFO during inflation."),
  q("A12","A","Comprehensive income includes:","Only net income","Net income plus other comprehensive income","Only unrealised gains","Only operating activities","B","Comprehensive income = Net income + Other comprehensive income (e.g., unrealised securities gains, foreign currency translation)."),
  q("A13","A","Treasury stock is recorded at:","Par value","Market value at reacquisition","Book value","Fair value at year-end","B","Treasury stock is recorded at cost (market value at the date of reacquisition)."),
  q("A14","A","A warranty obligation is recognised as:","An expense when paid","A contingent liability only","An expense when the product is sold","An asset","C","The matching principle requires warranty expense to be recognised in the period of the related sale."),
  q("A15","A","Under US GAAP, research costs are:","Capitalised","Expensed as incurred","Deferred and amortised","Treated as intangibles","B","Under US GAAP, both research and development costs are generally expensed as incurred."),

  // ── Section B: Planning, Budgeting & Forecasting ──
  q("B1","B","A master budget begins with:","Production budget","Sales budget","Cash budget","Direct labour budget","B","The sales budget is the starting point; all other budgets flow from the sales forecast."),
  q("B2","B","Zero-based budgeting requires managers to:","Justify only new expenditure","Justify all expenditure from scratch","Use last year's figures as a base","Focus only on variable costs","B","ZBB starts from zero — every cost must be justified, not just changes from the prior period."),
  q("B3","B","A flexible budget adjusts for changes in:","Selling price","Activity level (volume)","Interest rates","Tax rates","B","A flexible budget is adjusted based on actual activity levels, making variances more meaningful."),
  q("B4","B","The high-low method is used to:","Estimate fixed and variable costs","Calculate standard costs","Determine transfer prices","Perform sensitivity analysis","A","The high-low method uses the highest and lowest activity data points to separate fixed and variable costs."),
  q("B5","B","In a learning curve, as cumulative production doubles, average time per unit:","Doubles","Stays constant","Decreases by a fixed percentage","Increases","C","The learning curve effect means average time per unit falls by a fixed percentage each time cumulative output doubles."),
  q("B6","B","Regression analysis in forecasting produces:","Exact predictions","Statistical estimates with an R² value","Only qualitative results","Break-even points","B","Regression analysis produces a best-fit line and R² (coefficient of determination) showing the goodness of fit."),
  q("B7","B","A rolling budget is one that:","Is updated every 5 years","Always extends a fixed period into the future","Is fixed at the start of the year","Is prepared only for capital projects","B","A rolling (continuous) budget is updated regularly so that it always covers a fixed future period (e.g., 12 months)."),
  q("B8","B","The cash budget is prepared:","Before the sales budget","After all operating budgets","Simultaneously with the production budget","Before the capital budget","B","The cash budget is the final operating budget, drawing from all other budgets to project cash inflows and outflows."),
  q("B9","B","A cost that changes in total in direct proportion to activity is:","Fixed cost","Variable cost","Mixed cost","Sunk cost","B","Variable costs change in total in direct proportion to changes in activity level."),
  q("B10","B","Budgetary slack occurs when managers:","Set aggressive targets","Deliberately underestimate revenues or overestimate costs","Use activity-based budgeting","Adopt kaizen budgeting","B","Budgetary slack is built-in cushion — managers understate revenues or overstate costs to make targets easier to hit."),
  q("B11","B","The production budget depends on:","Sales budget and desired ending inventory","Cash budget","Capital budget","Labour budget only","A","Production = Sales + Desired Ending Inventory − Beginning Inventory."),
  q("B12","B","Top-down budgeting is characterised by:","Budgets prepared by lower-level managers","Senior management setting overall targets","Participative goal-setting","Activity-based cost allocation","B","In top-down budgeting, senior management sets the targets, which are then handed down to departments."),
  q("B13","B","Sensitivity analysis answers the question:","What is the best-case scenario?","What happens to the outcome if one variable changes?","What is the probability of achieving the budget?","How should costs be allocated?","B","Sensitivity ('what-if') analysis tests how the outcome changes when a single input variable is varied."),
  q("B14","B","A mission statement describes:","Specific financial targets","The organisation's fundamental purpose","Annual operating plans","Department-level KPIs","B","A mission statement articulates the organisation's core purpose and reason for existence."),
  q("B15","B","Kaizen budgeting incorporates:","Historical cost trends","Continuous improvement targets","Competitor benchmarks only","Zero-based assumptions","B","Kaizen budgeting builds in incremental improvement targets, reflecting the kaizen philosophy of continuous improvement."),

  // ── Section C: Performance Management ──
  q("C1","C","A favourable direct material price variance means:","More material was used than standard","Material was purchased at less than standard price","Less material was used","Production exceeded standard","B","Price variance = (Standard price − Actual price) × Actual quantity. Favourable = actual price < standard price."),
  q("C2","C","Return on Investment (ROI) is calculated as:","Net income / Total assets","Operating income / Average invested assets","Net income / Sales","Gross profit / Total assets","B","ROI = Operating income / Average invested assets — the primary performance measure for investment centres."),
  q("C3","C","Residual income is:","ROI minus cost of capital","Operating income minus a capital charge","Net income minus dividends","EBITDA minus depreciation","B","RI = Operating income − (Required rate of return × Invested assets). It avoids the ROI problem of rejecting positive-NPV investments."),
  q("C4","C","A favourable sales volume variance indicates:","Selling price was higher than budget","More units were sold than budgeted","Fixed costs were lower than budget","Variable costs were lower than budget","B","Sales volume variance compares actual vs budgeted units sold; favourable = actual > budget."),
  q("C5","C","Overhead is under-applied when:","Actual overhead < applied overhead","Applied overhead < actual overhead","Actual hours < standard hours","Production exceeds budget","B","Under-applied overhead means applied overhead < actual overhead incurred — the cost was under-absorbed."),
  q("C6","C","A profit centre manager is responsible for:","Revenue only","Costs only","Both revenues and costs","Revenues, costs, and invested capital","C","A profit centre manager controls both revenues and costs but not the level of investment."),
  q("C7","C","Transfer pricing at market price is most appropriate when:","There is no external market","The selling division has excess capacity","A competitive external market exists","Tax minimisation is the goal","C","Market-based transfer prices are ideal when an active, competitive external market exists for the transferred goods."),
  q("C8","C","A balanced scorecard typically includes which perspective?","Customer perspective","Competitor perspective","Supplier perspective","Regulatory perspective","A","The BSC has four perspectives: Financial, Customer, Internal Business Process, and Learning & Growth."),
  q("C9","C","Direct labour efficiency variance measures:","Wage rate difference","Difference between actual and standard hours worked","Difference between actual and budgeted output","Overtime premium","B","Labour efficiency variance = (Standard hours − Actual hours) × Standard rate."),
  q("C10","C","The contribution margin ratio is:","Fixed costs / Sales","Contribution margin / Sales","Net income / Sales","Variable costs / Sales","B","CM ratio = Contribution margin / Sales. It shows how much of each sales dollar covers fixed costs and profit."),
  q("C11","C","Economic Value Added (EVA) is:","Net income minus taxes","NOPAT minus (WACC × invested capital)","Revenue minus total costs","Operating income minus interest","B","EVA = NOPAT − (WACC × Invested Capital). Positive EVA means the firm earns above its cost of capital."),
  q("C12","C","A cost centre manager is evaluated on:","Profit generated","Costs incurred relative to budget","Return on assets","Revenue generated","B","Cost centre managers are responsible only for controllable costs — evaluated against budget."),
  q("C13","C","Market share variance measures:","Price differences vs competitors","Actual vs expected market share","Sales volume from industry growth vs market share change","Fixed cost absorption","C","Market share variance isolates the effect of gaining or losing market share vs the industry volume variance."),
  q("C14","C","The primary limitation of ROI as a performance measure is:","It ignores asset values","Managers may reject projects that would increase firm value","It is difficult to calculate","It excludes revenue","B","ROI can cause managers to reject positive-NPV investments if they lower the division's ROI, a sub-optimisation problem."),
  q("C15","C","Responsibility accounting assigns costs to:","The department that causes them","Corporate headquarters","The highest-cost centre","Shared service centres only","A","Responsibility accounting holds managers accountable for costs (and revenues) within their control."),

  // ── Section D: Cost Management ──
  q("D1","D","Activity-based costing (ABC) allocates overhead based on:","Direct labour hours","Machine hours","Cost drivers for each activity","Units produced","C","ABC identifies activities, assigns costs to activities, then allocates to products based on their consumption of each activity's cost driver."),
  q("D2","D","A sunk cost is:","A future cost that can be avoided","A cost already incurred and irrelevant to future decisions","A variable cost","A direct cost","B","Sunk costs are past costs that cannot be recovered — they are irrelevant to future decision-making."),
  q("D3","D","Under absorption costing, fixed manufacturing overhead is:","Expensed in the period incurred","Included in product cost","Excluded from product cost","Treated as a period cost","B","Absorption costing includes fixed manufacturing overhead in product cost (inventoriable cost)."),
  q("D4","D","In process costing, equivalent units represent:","Actual completed units","Partially complete units converted to their full-unit equivalent","Units transferred to finished goods","Units started during the period","B","Equivalent units convert partially completed units into their whole-unit equivalent for cost calculation purposes."),
  q("D5","D","Joint costs are allocated to joint products using which method?","FIFO","Relative sales value at split-off","Weighted average","Standard cost","B","The relative sales value method is the most common approach to allocating joint costs to joint products."),
  q("D6","D","Just-in-time (JIT) inventory aims to:","Maximise safety stock","Eliminate waste by receiving materials only when needed","Increase warehouse capacity","Use LIFO costing","B","JIT reduces inventory carrying costs and waste by synchronising material arrival with production needs."),
  q("D7","D","The value chain includes:","Only manufacturing activities","All activities from design to customer service","Only selling activities","Only support activities","B","The value chain encompasses all primary and support activities that create value, from R&D through customer service."),
  q("D8","D","Variable costing treats fixed manufacturing overhead as:","A product cost","A period cost","A mixed cost","An asset","B","Under variable costing, fixed manufacturing overhead is expensed in the period incurred, not inventoried."),
  q("D9","D","A by-product has:","High relative sales value","Low relative sales value","Equal value to the main product","No market value","B","By-products have relatively minor sales value compared to the main (joint) products."),
  q("D10","D","The reciprocal method of service cost allocation:","Ignores inter-department services","Partially recognises inter-department services","Fully recognises inter-department services","Uses direct allocation only","C","The reciprocal method fully recognises services between service departments using simultaneous equations."),
  q("D11","D","Life-cycle costing considers costs:","Only during production","From product design through disposal","Only during the sales phase","Only post-production","B","Life-cycle costing tracks costs across the entire product life cycle from design and development to disposal."),
  q("D12","D","Throughput costing treats which costs as product costs?","Fixed overhead","Direct material only","All variable costs","All manufacturing costs","B","Throughput costing (theory of constraints) treats only direct materials as product costs; all other costs are period costs."),
  q("D13","D","A cost driver in ABC is:","Any overhead cost","The factor that causes an activity cost to change","The total production output","The direct labour rate","B","A cost driver is the factor that causes the cost of an activity to increase or decrease — the basis for allocation in ABC."),
  q("D14","D","Quality costs include which type?","Prevention, appraisal, internal failure, external failure","Only internal failure costs","Only external failure costs","Only prevention costs","A","Quality costs are categorised as: Prevention (avoid defects), Appraisal (inspection), Internal failure (before delivery), External failure (after delivery)."),
  q("D15","D","The make-or-buy decision should consider:","Only variable costs","Relevant incremental costs and opportunity costs","Sunk costs","Historical full costs","B","Make-or-buy decisions should focus on relevant (avoidable) costs and opportunity costs, ignoring sunk costs."),

  // ── Section E: Internal Controls ──
  q("E1","E","The COSO framework identifies how many components of internal control?","3","5","7","9","B","COSO's Internal Control — Integrated Framework has five components: Control Environment, Risk Assessment, Control Activities, Information & Communication, and Monitoring."),
  q("E2","E","Segregation of duties separates which functions?","Recording and approving","Authorisation, custody, and recording","Purchasing and selling","Budgeting and reporting","B","Effective segregation of duties separates: authorisation of transactions, custody of assets, and recording/reconciliation."),
  q("E3","E","Sarbanes-Oxley Section 404 requires management to:","File quarterly earnings reports","Assess and report on internal controls over financial reporting","Certify tax returns","Register securities","B","SOX Section 404 requires management to assess the effectiveness of internal controls over financial reporting, with auditor attestation."),
  q("E4","E","An unqualified audit opinion means:","The financial statements contain errors","The financial statements present fairly in all material respects","The auditor disagrees with management","The audit was not completed","B","An unqualified (clean) opinion means the financial statements are fairly presented in accordance with GAAP."),
  q("E5","E","Business continuity planning ensures:","Maximum profitability","Operations can recover after a disruption","Zero system downtime always","Regulatory compliance only","B","BCP ensures that critical business operations can continue or quickly resume after a disaster or major disruption."),
  q("E6","E","A preventive control is designed to:","Detect errors after they occur","Correct errors that have occurred","Stop errors or irregularities from occurring","Report errors to management","C","Preventive controls (e.g., access passwords, authorisation requirements) prevent errors or fraud before they happen."),
  q("E7","E","The Foreign Corrupt Practices Act (FCPA) prohibits:","Domestic bribery","Bribing foreign government officials for business","Tax evasion","Import violations","B","The FCPA prohibits US companies (and listed foreign companies) from bribing foreign government officials to obtain or retain business."),
  q("E8","E","IT general controls include:","Application-specific input edits","Access controls over systems and data","Report formatting","Data entry procedures","B","IT general controls (e.g., access controls, change management, operations) apply across all IT systems and applications."),
  q("E9","E","A detective control is designed to:","Prevent fraud","Identify errors or irregularities that have already occurred","Authorise transactions","Process transactions","B","Detective controls (e.g., reconciliations, audits, exception reports) identify problems after they have occurred."),
  q("E10","E","The audit committee of a board should consist of:","Management representatives","Independent directors","External auditors","Shareholders","B","The audit committee should be composed of independent (non-executive) directors to provide objective oversight."),
  q("E11","E","A phishing attack is:","A hardware failure","A social engineering attack using deceptive emails","A denial-of-service attack","A SQL injection attack","B","Phishing uses fraudulent emails to trick users into revealing credentials or installing malware."),
  q("E12","E","The control environment refers to:","Specific control procedures","The overall attitude and awareness toward internal controls","IT system controls","Budget controls","B","The control environment sets the tone of the organisation — management's philosophy and commitment to integrity and ethics."),
  q("E13","E","Which risk response involves transferring risk to another party?","Risk avoidance","Risk sharing (transfer)","Risk reduction","Risk acceptance","B","Risk transfer (e.g., insurance, outsourcing) shifts the financial consequences of a risk to another party."),
  q("E14","E","Compensating controls are used when:","Primary controls work correctly","A primary control is absent or ineffective","Segregation of duties exists","No risk is identified","B","Compensating controls reduce risk when the ideal primary control cannot be implemented (e.g., due to size constraints)."),
  q("E15","E","Data encryption protects information by:","Deleting sensitive data","Converting data to unreadable format without a key","Backing up data","Restricting physical access","B","Encryption converts data into ciphertext that can only be read with the correct decryption key."),

  // ── Section F: Technology and Analytics ──
  q("F1","F","Big data is characterised by which 'V's?","Value and velocity only","Volume, velocity, and variety","Volume and value only","Velocity and veracity only","B","Big data is typically described by the three (or more) Vs: Volume (size), Velocity (speed), and Variety (data types)."),
  q("F2","F","A data warehouse is best described as:","A transactional database","A centralised repository for structured historical data for reporting","A cloud storage system","A real-time processing engine","B","A data warehouse consolidates structured data from multiple sources for analytical reporting and business intelligence."),
  q("F3","F","Machine learning is a subset of:","Blockchain","Artificial intelligence","Cloud computing","ERP systems","B","Machine learning is a branch of artificial intelligence that enables systems to learn and improve from experience."),
  q("F4","F","Descriptive analytics answers the question:","What will happen?","What should we do?","What happened?","Why did it happen?","C","Descriptive analytics summarises historical data to answer 'what happened?' — the most basic level of analytics."),
  q("F5","F","A relational database stores data in:","Hierarchical trees","Tables with rows and columns","Key-value pairs only","Document format","B","Relational databases organise data into tables (relations) with rows and columns, linked by keys."),
  q("F6","F","Blockchain is best described as:","A centralised database controlled by one entity","A distributed, immutable ledger","A type of cloud computing","An AI algorithm","B","Blockchain is a decentralised, distributed ledger where records are immutable once added and validated by consensus."),
  q("F7","F","Predictive analytics uses:","Only historical data summaries","Statistical models and machine learning to forecast future outcomes","Real-time data only","Blockchain technology","B","Predictive analytics applies statistical and machine learning models to historical data to forecast future events."),
  q("F8","F","An ERP system integrates:","Only financial modules","All business processes into one unified system","Only HR and payroll","Supply chain only","B","ERP (Enterprise Resource Planning) integrates all core business processes — finance, HR, supply chain, manufacturing — into a single system."),
  q("F9","F","A ransomware attack:","Steals data silently","Encrypts data and demands payment for decryption","Crashes the network","Monitors user activity","B","Ransomware encrypts victim files and demands a ransom payment (usually cryptocurrency) for the decryption key."),
  q("F10","F","Cloud computing's 'SaaS' model provides:","Infrastructure as a service","Software applications over the internet","Platform for development","Hardware resources","B","SaaS (Software as a Service) delivers software applications over the internet on a subscription basis."),
  q("F11","F","Data visualisation tools are primarily used to:","Store large datasets","Present data insights in graphical format","Encrypt sensitive data","Perform SQL queries","B","Data visualisation tools (e.g., dashboards, charts) present data insights visually to aid understanding and decision-making."),
  q("F12","F","The primary risk of using a data lake is:","High storage cost","Becoming a 'data swamp' with poor governance","Lack of storage capacity","Limited data variety","B","Without strong governance, data lakes can become 'data swamps' — repositories of raw, unorganised, unusable data."),
  q("F13","F","Process automation using RPA (Robotic Process Automation) is best suited for:","Complex judgment-based tasks","Repetitive, rule-based tasks","Creative design work","Strategic planning","B","RPA automates repetitive, structured, rule-based tasks by mimicking user interactions with software systems."),
  q("F14","F","The primary benefit of cloud computing for organisations is:","Eliminating all IT costs","Scalability and reduced infrastructure investment","Full data control","Guaranteed uptime","B","Cloud computing provides on-demand scalability, reducing capital expenditure on physical infrastructure."),
  q("F15","F","Sensitivity analysis in analytics is used to:","Store data securely","Test how output changes when input variables are varied","Visualise data","Train machine learning models","B","Sensitivity analysis (what-if analysis) tests how changes in input assumptions affect the model's output."),
];

export const SECTIONS_LIST = ["A","B","C","D","E","F"] as const;
export type SectionId = typeof SECTIONS_LIST[number];

export function getQuestionsForSection(section: SectionId): MCQ[] {
  return DIAGNOSTIC_QUESTIONS.filter(q => q.section === section);
}
